# Settings that the LAMMPS build will import when this package library is used
#
nufeb_SYSINC = -std=c++1y -DENABLE_DUMP_GRID -I/usr/local/include/vtk-6.3 -DENABLE_DUMP_BIO_HDF5 -I../../../thirdparty/hdf5/hdf5/include
nufeb_SYSLIB = -lvtksys-6.3 -lvtkCommonCore-6.3 -lvtkCommonExecutionModel-6.3 -lvtkCommonMisc-6.3 -lvtkCommonMath-6.3 -lvtkCommonSystem-6.3 -lvtkCommonTransforms-6.3 -lvtkIOCore-6.3 -lvtkIOXML-6.3 -lvtkIOXMLParser-6.3 -lvtkIOLegacy-6.3 -lvtkIOParallelXML-6.3 -lvtkCommonDataModel-6.3 -lvtkParallelCore-6.3 -lhdf5
nufeb_SYSPATH = -I/usr/local/include/vtk-6.3 -I../../../thirdparty/hdf5/hdf5/include
