name: Merge Upstream

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge-master:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Merge upstream
          run: |
            git config --global user.name Jsakkos
            git config --global user.email jonathansakkos@protonmail.com
            # "git checkout master" is unnecessary, already here by default
            git pull --unshallow  # this option is very important, you would get
                                  # complains about unrelated histories without it.
                                  # (but actions/checkout@v2 can also be instructed
                                  # to fetch all git depth right from the start)
            git remote add upstream https://github.com/nufeb/NUFEB
            git fetch upstream
            git merge --no-edit upstream/master
            git push origin master
  merge-cyano:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Merge master
          run: |
            git checkout -b cyano
            git fetch origin
            git merge origin/master
            git push origin cyano
